# Berkas dbt/dbt_project.yml
# Konfigurasi dbt untuk project Smart Logistics.

name: smart_logistics
version: "1.0.0"
config-version: 2

profile: smart_logistics

model-paths: ["models"]
target-path: "target"

models:
  smart_logistics:
    staging:
      +materialized: view
    marts:
      +materialized: table
